apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-kata
  labels:
    app: image-processing-kata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-processing-kata
  template:
    metadata:
      labels:
        app: image-processing-kata
    spec:
      runtimeClassName: kata-fc
      containers:
      - name: image-processing
        image: stav1212/image_processing:v51
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: image-processing-kata-service
  labels:
    app: image-processing-kata
spec:
  selector:
    app: image-processing-kata
  ports:
  - name: web
    port: 80
    targetPort: 8080
    nodePort: 30885
  type: NodePort
